/* eslint-disable no-console -- build-time CLI script; stdout/stderr are its intended output. */
// Compiles Maizzle email templates to placeholder-preserving HTML layouts at BUILD time.
// Maizzle (@maizzle/framework) is a devDependency and runs only here — it never enters
// the published runtime bundle. Output modules are consumed by the runtime renderer.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { render } from '@maizzle/framework';
import config from '../maizzle.config.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'src/runtime/emails/compiled');

// Configurable template source list — v1 has only this app's `emails/`.
// This array is the seam future essentials apps' template dirs extend.
const templateDirs = [join(root, 'emails')];

mkdirSync(outDir, { recursive: true });

const toCamel = (name) => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

let count = 0;
for (const dir of templateDirs) {
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.vue'))) {
    const name = basename(file, '.vue');
    const source = readFileSync(join(dir, file), 'utf8');
    const { html } = await render(source, config);
    const out = `// GENERATED by scripts/build-emails.mjs — do not edit.\nexport const ${toCamel(name)}Layout = ${JSON.stringify(html)};\n`;
    writeFileSync(join(outDir, `${name}.ts`), out);
    console.log(`[build-emails] ${file} -> src/runtime/emails/compiled/${name}.ts (${html.length} bytes)`);
    count++;
  }
}

if (count === 0) {
  console.error('[build-emails] no .vue templates found');
  process.exit(1);
}
